### @name="Get all products"
GET  http://localhost:8080/api/products
Accept: application/json


### @name="Get products by id"
GET  http://localhost:8080/api/products/356
Accept: application/json


### @name="Get products by range"
GET  http://localhost:8080/api/products?low=40000&high=100000
Accept: application/json



### @name="add a new product"
POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Wacom",
  "price": 5400.00,
  "quantity": 100
}



### @name="add a invalid product"
POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": -5400.00,
  "quantity": 0
}

### @name="update product price"
PATCH http://localhost:8080/api/products/1?price=75000.90
Accept: application/json

